/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/capabilities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Capabilities */
    get: operations["capabilities_api_capabilities_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/taxonomy": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Taxonomy */
    get: operations["taxonomy_api_taxonomy_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Overview */
    get: operations["overview_api_overview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Catalog */
    get: operations["catalog_api_projects_get"];
    put?: never;
    /** Add Project */
    post: operations["add_project_api_projects_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/catalog/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Export Catalog */
    get: operations["export_catalog_api_catalog_export_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{pid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Project */
    get: operations["get_project_api_projects__pid__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{pid}/assets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload */
    post: operations["upload_api_projects__pid__assets_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/assets/{aid}/content": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Media */
    get: operations["media_api_assets__aid__content_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/assets/{aid}/frames/{index}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Frame */
    get: operations["frame_api_assets__aid__frames__index__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{rid}/assets/{aid}/frames/{index}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Run Frame */
    get: operations["run_frame_api_runs__rid__assets__aid__frames__index__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** History */
    get: operations["history_api_runs_get"];
    put?: never;
    /** Create Run */
    post: operations["create_run_api_runs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{rid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Run */
    get: operations["get_run_api_runs__rid__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{rid}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel */
    post: operations["cancel_api_runs__rid__cancel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/runs/{rid}/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Export */
    get: operations["export_api_runs__rid__export_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/review": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Queue */
    get: operations["queue_api_review_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{pid}/reviews": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Review */
    post: operations["review_api_projects__pid__reviews_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bulk/dry-run": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Bulk */
    post: operations["bulk_api_bulk_dry_run_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/roadmap": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Roadmap */
    get: operations["roadmap_api_roadmap_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Experiments */
    get: operations["experiments_api_experiments_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AssetView */
    AssetView: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Kind */
      kind: string;
      /** Sha256 */
      sha256: string;
      /** Bytes */
      bytes: number;
      /** Width */
      width?: number | null;
      /** Height */
      height?: number | null;
      /** Duration */
      duration?: number | null;
      /** Url */
      url: string;
      /** Frames */
      frames?: {
        [key: string]: unknown;
      }[];
    };
    /** Capabilities */
    Capabilities: {
      /**
       * Environment
       * @default Private local workspace
       */
      environment: string;
      /** User */
      user: string;
      /** Role */
      role: string;
      /**
       * Live Enabled
       * @default false
       */
      live_enabled: boolean;
      /**
       * Live Reason
       * @default No numeric API budget authorized. Live analysis is disabled.
       */
      live_reason: string;
      /**
       * Images
       * @default true
       */
      images: boolean;
      /** Video */
      video: boolean;
      /**
       * Video Status
       * @default Experimental preprocessing; temporal recognition not validated
       */
      video_status: string;
      /**
       * Max Images
       * @default 8
       */
      max_images: number;
      /**
       * Max Image Bytes
       * @default 5242880
       */
      max_image_bytes: number;
      /**
       * Max Video Bytes
       * @default 41943040
       */
      max_video_bytes: number;
      /**
       * Max Video Seconds
       * @default 60
       */
      max_video_seconds: number;
      /**
       * Taxonomy Version
       * @default 4.1
       */
      taxonomy_version: string;
      /**
       * Runtime
       * @default Local API responding; coding-agent runtime unknown
       */
      runtime: string;
      /** Providers */
      providers: {
        [key: string]: boolean;
      };
    };
    /** CatalogPage */
    CatalogPage: {
      /** Items */
      items: components["schemas"]["ProjectView"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** ProjectCreate */
    ProjectCreate: {
      /** Title */
      title: string;
      /**
       * Release
       * @default Unspecified release
       */
      release: string;
      /**
       * Platform
       * @default pc
       * @enum {string}
       */
      platform: "pc" | "console" | "mobile" | "multiplatform";
      /**
       * Entry
       * @default publisher_project
       * @enum {string}
       */
      entry: "publisher_project" | "game_reference" | "demo";
      /**
       * Association Confirmed
       * @default false
       */
      association_confirmed: boolean;
      /**
       * Description
       * @default
       */
      description: string;
      /**
       * Source Label
       * @default User-supplied description
       */
      source_label: string;
      /**
       * Reference Url
       * @default
       */
      reference_url: string;
    };
    /** ProjectView */
    ProjectView: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Release */
      release: string;
      /** Platform */
      platform: string;
      /** Entry */
      entry: string;
      /** Identity Status */
      identity_status: string;
      /** Created At */
      created_at: string;
      /** Approved Primary */
      approved_primary?: string | null;
      /** Approved Primary Label */
      approved_primary_label?: string | null;
      /**
       * Review Version
       * @default 0
       */
      review_version: number;
      /**
       * Run Count
       * @default 0
       */
      run_count: number;
      /** Assets */
      assets?: components["schemas"]["AssetView"][];
    };
    /** ReviewCreate */
    ReviewCreate: {
      /**
       * Kind
       * @enum {string}
       */
      kind: "primary" | "identity" | "attribute";
      /** Value */
      value: string;
      /** Property Id */
      property_id?: string | null;
      /** Reason */
      reason: string;
      /** Expected Version */
      expected_version: number;
    };
    /** RunCreate */
    RunCreate: {
      /** Project Id */
      project_id: string;
      /**
       * Mode
       * @default offline
       * @enum {string}
       */
      mode: "offline" | "live";
      /** Idempotency Key */
      idempotency_key: string;
    };
    /** RunView */
    RunView: {
      /** Id */
      id: string;
      /** Project Id */
      project_id: string;
      /** Title */
      title: string;
      /** Release */
      release: string;
      /** Platform */
      platform: string;
      /** Mode */
      mode: string;
      /**
       * Dataset
       * @default workspace
       * @enum {string}
       */
      dataset: "workspace" | "demo";
      /** Status */
      status: string;
      /** Identity Status */
      identity_status: string;
      /** Created At */
      created_at: string;
      /** Primary Genre */
      primary_genre?: string | null;
      /** Primary Label */
      primary_label?: string | null;
      /** Primary Status */
      primary_status: string;
      /** Blocker */
      blocker?: string | null;
      /** Events */
      events?: {
        [key: string]: unknown;
      }[];
      /** Tags */
      tags?: components["schemas"]["TagView"][];
      /** Observations */
      observations?: {
        [key: string]: unknown;
      }[];
      /** Assets */
      assets?: components["schemas"]["AssetView"][];
      /** Provenance */
      provenance?: {
        [key: string]: unknown;
      };
      /** Alternatives */
      alternatives?: {
        [key: string]: unknown;
      }[];
      /** Distributions */
      distributions?: {
        [key: string]: unknown;
      };
      /** Reviews */
      reviews?: {
        [key: string]: unknown;
      }[];
    };
    /** TagView */
    TagView: {
      /** Id */
      id: string;
      /** Label */
      label: string;
      /** Category */
      category: string;
      /** State */
      state?: string | null;
      /** Human State */
      human_state?: string | null;
      /** Execution */
      execution: string;
      /** Action */
      action?: string | null;
      /** Probabilities */
      probabilities?: {
        [key: string]: number;
      } | null;
      /**
       * Support Status
       * @default Evaluated context; specific support not yet verified.
       */
      support_status: string;
      /** Context Evidence Ids */
      context_evidence_ids?: string[];
      /** Support Links */
      support_links?: {
        [key: string]: unknown;
      }[];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  capabilities_api_capabilities_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Capabilities"];
        };
      };
    };
  };
  taxonomy_api_taxonomy_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  overview_api_overview_get: {
    parameters: {
      query?: {
        dataset?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  catalog_api_projects_get: {
    parameters: {
      query?: {
        q?: string;
        platform?: string;
        genre?: string;
        family?: string;
        review?: string;
        input_type?: string;
        attribute?: string;
        state?: string;
        dataset?: string;
        page?: number;
        page_size?: number;
        sort?: string;
        after?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CatalogPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_project_api_projects_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  export_catalog_api_catalog_export_get: {
    parameters: {
      query?: {
        format?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_project_api_projects__pid__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  upload_api_projects__pid__assets_post: {
    parameters: {
      query?: {
        name?: string;
        kind?: string;
      };
      header?: never;
      path: {
        pid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  media_api_assets__aid__content_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        aid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  frame_api_assets__aid__frames__index__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        aid: string;
        index: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  run_frame_api_runs__rid__assets__aid__frames__index__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        rid: string;
        aid: string;
        index: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  history_api_runs_get: {
    parameters: {
      query?: {
        project_id?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunView"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_run_api_runs_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RunCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_run_api_runs__rid__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        rid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cancel_api_runs__rid__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        rid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  export_api_runs__rid__export_get: {
    parameters: {
      query?: {
        format?: string;
      };
      header?: never;
      path: {
        rid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  queue_api_review_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  review_api_projects__pid__reviews_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReviewCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  bulk_api_bulk_dry_run_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  roadmap_api_roadmap_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  experiments_api_experiments_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
